### PR TITLE
Added framOn toggle option to parameter dictionary

### PR DESCRIPTION
**Pull request by hymanjd**
Does the same thing as disbleFram, but is a more natural True and False. 

disableFram == True is the same as frameOn == False (FRAM will not be used in dfnGen)

disableFram == False is the same as frameOn == True (FRAM will be used in dfnGen)

### CODE REVIEW

**Review by aidanstansberry — CHANGES_REQUESTED** [review]
Just one non consequential issue I saw. Everything else appeared to be running fine.

**Comment by hymanjd** [comment]
Where is that issue?

**Review by aidanstansberry — COMMENTED** [review]
Sorry, I thought I left a comment on the code. Warning message twice unless we change this line from if to elif

    if not params['framOn']['value']:
        hf.print_warning(
            "Running with FRAM off. Mesh will not work for DFN flow and transport."
        )
        params['disableFram']['value'] = True

--> 
    elif not params['framOn']['value']:
        hf.print_warning(
            "Running with FRAM off. Mesh will not work for DFN flow and transport."
        )
        params['disableFram']['value'] = True

**Comment by hymanjd** [comment]
That logic is correct as written. The first logic statements are to check compatibility, the second is to print the warning.

**Review by aidanstansberry — COMMENTED** [review]
Sorry, one more step back. This is the entire statement. As written if the first statement is true it prints a warning, and also sets a value for 'framOn'. This then gets done a second time which is redundant and also reprints the error message. As I said before it is a non consequential error because all that happens is the same thing gets printed twice.   

  if params['disableFram']['value']:
        hf.print_warning(
            "Running with FRAM off. Mesh will not work for DFN flow and transport."
        )
        params['framOn']['value'] = False

  if not params['framOn']['value']:
        hf.print_warning(
            "Running with FRAM off. Mesh will not work for DFN flow and transport."
        )
        params['disableFram']['value'] = True


The second if statement should be an elif to avoid redundancy

**Comment by hymanjd** [comment]
Gotcha. I think it's fine.

**Review by aidanstansberry — APPROVED** [review]

**Pull request merged**
