### PR TITLE
Functionality for converting graphs.

### PR DESCRIPTION
**Pull request by janozeeth**
Functionality for converting intersection to fracture graphs, and vice versa. Extends intersection (fracture) graph into a bipartite graph of fractures and intersections, then projects onto fractures (intersections).

### CODE REVIEW

**Review by hymanjd — CHANGES_REQUESTED** [review]
This is a great start. 

A few things. 

1. First, please put in docstrings for all the functions. See other functions in the repo for examples. 
2. Function names. We are trying to you underscore formatting without numbers.  So, fracture2intersection would be fracture_to_intersection. 
3. Can we create a driver named something like convert_graph with takes in the graph object and the desired output? Then these functions are called by logic under the hood.

Once this is all done, I'll work out how to integrate everything into the workflow with the dfn object.

**Comment by janozeeth** [comment]
Apologies for the late reply on this. I've been absolutely slammed the last couple weeks (not an excuse, of course). Just wanted to provide a heads up that I will be working on these and send some appreciation for the feedback (thank you!). I'll make another push when I get the docstrings and driver function up, plus function names changed. All should be pretty easy.

**Comment by hymanjd** [comment]
Sounds good! Reach out if you need help.
________________________________
From: rshaver ***@***.***>
Sent: Monday, October 23, 2023 3:55:47 PM
To: lanl/dfnWorks ***@***.***>
Cc: Hyman, Jeffrey De'Haven ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [lanl/dfnWorks] Functionality for converting graphs. (PR #66)


Apologies for the late reply on this. I've been absolutely slammed the last couple weeks (not an excuse, of course). Just wanted to provide a heads up that I will be working on these and send some appreciation for the feedback (thank you!). I'll make another push when I get the docstrings and driver function up, plus function names changed. All should be pretty easy.

**Comment by janozeeth** [comment]
Just pushed the changes you requested a few months ago. Apologies again for the delay. Let me know if there's anything else that looks awry.

**Review by hymanjd — APPROVED** [review]
looks great! Thanks, Ryan.

**Pull request merged**
